// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaBliznyk/newsportal/internal/domain"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CountNews provides a mock function with given fields: ctx, req
func (_m *Service) CountNews(ctx context.Context, req domain.CountNewsReq) (*domain.CountNewsResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountNews")
	}

	var r0 *domain.CountNewsResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CountNewsReq) (*domain.CountNewsResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CountNewsReq) *domain.CountNewsResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CountNewsResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CountNewsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CountNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountNews'
type Service_CountNews_Call struct {
	*mock.Call
}

// CountNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CountNewsReq
func (_e *Service_Expecter) CountNews(ctx interface{}, req interface{}) *Service_CountNews_Call {
	return &Service_CountNews_Call{Call: _e.mock.On("CountNews", ctx, req)}
}

func (_c *Service_CountNews_Call) Run(run func(ctx context.Context, req domain.CountNewsReq)) *Service_CountNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CountNewsReq))
	})
	return _c
}

func (_c *Service_CountNews_Call) Return(_a0 *domain.CountNewsResp, _a1 error) *Service_CountNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CountNews_Call) RunAndReturn(run func(context.Context, domain.CountNewsReq) (*domain.CountNewsResp, error)) *Service_CountNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function with given fields: ctx
func (_m *Service) GetCategories(ctx context.Context) (*domain.GetCategoriesResp, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 *domain.GetCategoriesResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.GetCategoriesResp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.GetCategoriesResp); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetCategoriesResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type Service_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) GetCategories(ctx interface{}) *Service_GetCategories_Call {
	return &Service_GetCategories_Call{Call: _e.mock.On("GetCategories", ctx)}
}

func (_c *Service_GetCategories_Call) Run(run func(ctx context.Context)) *Service_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_GetCategories_Call) Return(_a0 *domain.GetCategoriesResp, _a1 error) *Service_GetCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetCategories_Call) RunAndReturn(run func(context.Context) (*domain.GetCategoriesResp, error)) *Service_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetNews provides a mock function with given fields: ctx, req
func (_m *Service) GetNews(ctx context.Context, req domain.GetNewsReq) (*domain.GetNewsResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetNews")
	}

	var r0 *domain.GetNewsResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetNewsReq) (*domain.GetNewsResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetNewsReq) *domain.GetNewsResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetNewsResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetNewsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNews'
type Service_GetNews_Call struct {
	*mock.Call
}

// GetNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetNewsReq
func (_e *Service_Expecter) GetNews(ctx interface{}, req interface{}) *Service_GetNews_Call {
	return &Service_GetNews_Call{Call: _e.mock.On("GetNews", ctx, req)}
}

func (_c *Service_GetNews_Call) Run(run func(ctx context.Context, req domain.GetNewsReq)) *Service_GetNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GetNewsReq))
	})
	return _c
}

func (_c *Service_GetNews_Call) Return(_a0 *domain.GetNewsResp, _a1 error) *Service_GetNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetNews_Call) RunAndReturn(run func(context.Context, domain.GetNewsReq) (*domain.GetNewsResp, error)) *Service_GetNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function with given fields: ctx
func (_m *Service) GetTags(ctx context.Context) (*domain.GetTagsResp, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 *domain.GetTagsResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.GetTagsResp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.GetTagsResp); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetTagsResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type Service_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) GetTags(ctx interface{}) *Service_GetTags_Call {
	return &Service_GetTags_Call{Call: _e.mock.On("GetTags", ctx)}
}

func (_c *Service_GetTags_Call) Run(run func(ctx context.Context)) *Service_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_GetTags_Call) Return(_a0 *domain.GetTagsResp, _a1 error) *Service_GetTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetTags_Call) RunAndReturn(run func(context.Context) (*domain.GetTagsResp, error)) *Service_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListNews provides a mock function with given fields: ctx, req
func (_m *Service) ListNews(ctx context.Context, req domain.ListNewsReq) (*domain.ListNewsResp, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListNews")
	}

	var r0 *domain.ListNewsResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListNewsReq) (*domain.ListNewsResp, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListNewsReq) *domain.ListNewsResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListNewsResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListNewsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNews'
type Service_ListNews_Call struct {
	*mock.Call
}

// ListNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ListNewsReq
func (_e *Service_Expecter) ListNews(ctx interface{}, req interface{}) *Service_ListNews_Call {
	return &Service_ListNews_Call{Call: _e.mock.On("ListNews", ctx, req)}
}

func (_c *Service_ListNews_Call) Run(run func(ctx context.Context, req domain.ListNewsReq)) *Service_ListNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListNewsReq))
	})
	return _c
}

func (_c *Service_ListNews_Call) Return(_a0 *domain.ListNewsResp, _a1 error) *Service_ListNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListNews_Call) RunAndReturn(run func(context.Context, domain.ListNewsReq) (*domain.ListNewsResp, error)) *Service_ListNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
