// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	NewsService struct{ List, Count, Get, Categories, Tags string }
}{
	NewsService: struct{ List, Count, Get, Categories, Tags string }{
		List:       "list",
		Count:      "count",
		Get:        "get",
		Categories: "categories",
		Tags:       "tags",
	},
}

func (NewsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"List": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "filter",
						Type:     smd.Object,
						TypeName: "NewsFilter",
						Properties: smd.PropertyList{
							{
								Name:        "CategoryID",
								Description: `Идентификатор категории`,
								Type:        smd.Integer,
							},
							{
								Name:        "TagID",
								Description: `Идентификатор тега`,
								Type:        smd.Integer,
							},
							{
								Name:        "From",
								Description: `Начало периода`,
								Type:        smd.String,
							},
							{
								Name:        "To",
								Description: `Конец периода`,
								Type:        smd.String,
							},
						},
					},
					{
						Name:     "pager",
						Type:     smd.Object,
						TypeName: "Pager",
						Properties: smd.PropertyList{
							{
								Name:        "Page",
								Description: `Номер страницы`,
								Type:        smd.Integer,
							},
							{
								Name:        "Limit",
								Description: `Количество на страницу`,
								Type:        smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]News",
					Items: map[string]string{
						"$ref": "#/definitions/News",
					},
					Definitions: map[string]smd.Definition{
						"News": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "preamble",
									Type: smd.String,
								},
								{
									Name: "content",
									Type: smd.String,
								},
								{
									Name: "author",
									Type: smd.String,
								},
								{
									Name: "created_at",
									Type: smd.String,
								},
								{
									Name: "published_at",
									Type: smd.String,
								},
								{
									Name:     "category",
									Optional: true,
									Ref:      "#/definitions/Category",
									Type:     smd.Object,
								},
								{
									Name: "tags",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/Tag",
									},
								},
							},
						},
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"Count": {
				Parameters: []smd.JSONSchema{
					{
						Name:     "filter",
						Type:     smd.Object,
						TypeName: "NewsFilter",
						Properties: smd.PropertyList{
							{
								Name:        "CategoryID",
								Description: `Идентификатор категории`,
								Type:        smd.Integer,
							},
							{
								Name:        "TagID",
								Description: `Идентификатор тега`,
								Type:        smd.Integer,
							},
							{
								Name:        "From",
								Description: `Начало периода`,
								Type:        smd.String,
							},
							{
								Name:        "To",
								Description: `Конец периода`,
								Type:        smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type: smd.Integer,
				},
			},
			"Get": {
				Parameters: []smd.JSONSchema{
					{
						Name: "id",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "News",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "preamble",
							Type: smd.String,
						},
						{
							Name: "content",
							Type: smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name: "created_at",
							Type: smd.String,
						},
						{
							Name: "published_at",
							Type: smd.String,
						},
						{
							Name:     "category",
							Optional: true,
							Ref:      "#/definitions/Category",
							Type:     smd.Object,
						},
						{
							Name: "tags",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Tag",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"Categories": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Category",
					Items: map[string]string{
						"$ref": "#/definitions/Category",
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"Tags": {
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Tag",
					Items: map[string]string{
						"$ref": "#/definitions/Tag",
					},
					Definitions: map[string]smd.Definition{
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s NewsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.NewsService.List:
		var args = struct {
			Filter NewsFilter `json:"filter"`
			Pager  Pager      `json:"pager"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"filter", "pager"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.List(ctx, args.Filter, args.Pager))

	case RPC.NewsService.Count:
		var args = struct {
			Filter NewsFilter `json:"filter"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"filter"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Count(ctx, args.Filter))

	case RPC.NewsService.Get:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Get(ctx, args.Id))

	case RPC.NewsService.Categories:
		resp.Set(s.Categories(ctx))

	case RPC.NewsService.Tags:
		resp.Set(s.Tags(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
