// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaBliznyk/newsportal/internal/domain"
)

// NewsRepository is an autogenerated mock type for the NewsRepository type
type NewsRepository struct {
	mock.Mock
}

type NewsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NewsRepository) EXPECT() *NewsRepository_Expecter {
	return &NewsRepository_Expecter{mock: &_m.Mock}
}

// CountNews provides a mock function with given fields: ctx, req
func (_m *NewsRepository) CountNews(ctx context.Context, req domain.CountNewsReq) (int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountNews")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CountNewsReq) (int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CountNewsReq) int); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CountNewsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewsRepository_CountNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountNews'
type NewsRepository_CountNews_Call struct {
	*mock.Call
}

// CountNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CountNewsReq
func (_e *NewsRepository_Expecter) CountNews(ctx interface{}, req interface{}) *NewsRepository_CountNews_Call {
	return &NewsRepository_CountNews_Call{Call: _e.mock.On("CountNews", ctx, req)}
}

func (_c *NewsRepository_CountNews_Call) Run(run func(ctx context.Context, req domain.CountNewsReq)) *NewsRepository_CountNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CountNewsReq))
	})
	return _c
}

func (_c *NewsRepository_CountNews_Call) Return(_a0 int, _a1 error) *NewsRepository_CountNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewsRepository_CountNews_Call) RunAndReturn(run func(context.Context, domain.CountNewsReq) (int, error)) *NewsRepository_CountNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function with given fields: ctx
func (_m *NewsRepository) GetCategories(ctx context.Context) ([]domain.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewsRepository_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type NewsRepository_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NewsRepository_Expecter) GetCategories(ctx interface{}) *NewsRepository_GetCategories_Call {
	return &NewsRepository_GetCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *NewsRepository_GetCategories_Call) Run(run func(ctx context.Context)) *NewsRepository_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *NewsRepository_GetCategories_Call) Return(_a0 []domain.Category, _a1 error) *NewsRepository_GetCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewsRepository_GetCategories_Call) RunAndReturn(run func(context.Context) ([]domain.Category, error)) *NewsRepository_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetNews provides a mock function with given fields: ctx, id
func (_m *NewsRepository) GetNews(ctx context.Context, id int) (*domain.News, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.News, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.News); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewsRepository_GetNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNews'
type NewsRepository_GetNews_Call struct {
	*mock.Call
}

// GetNews is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *NewsRepository_Expecter) GetNews(ctx interface{}, id interface{}) *NewsRepository_GetNews_Call {
	return &NewsRepository_GetNews_Call{Call: _e.mock.On("GetNews", ctx, id)}
}

func (_c *NewsRepository_GetNews_Call) Run(run func(ctx context.Context, id int)) *NewsRepository_GetNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *NewsRepository_GetNews_Call) Return(_a0 *domain.News, _a1 error) *NewsRepository_GetNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewsRepository_GetNews_Call) RunAndReturn(run func(context.Context, int) (*domain.News, error)) *NewsRepository_GetNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function with given fields: ctx
func (_m *NewsRepository) GetTags(ctx context.Context) ([]domain.Tag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []domain.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Tag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Tag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewsRepository_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type NewsRepository_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NewsRepository_Expecter) GetTags(ctx interface{}) *NewsRepository_GetTags_Call {
	return &NewsRepository_GetTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *NewsRepository_GetTags_Call) Run(run func(ctx context.Context)) *NewsRepository_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *NewsRepository_GetTags_Call) Return(_a0 []domain.Tag, _a1 error) *NewsRepository_GetTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewsRepository_GetTags_Call) RunAndReturn(run func(context.Context) ([]domain.Tag, error)) *NewsRepository_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListNews provides a mock function with given fields: ctx, req
func (_m *NewsRepository) ListNews(ctx context.Context, req domain.ListNewsReq) ([]domain.ListNewsItem, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListNewsByFilter")
	}

	var r0 []domain.ListNewsItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListNewsReq) ([]domain.ListNewsItem, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListNewsReq) []domain.ListNewsItem); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ListNewsItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListNewsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewsRepository_ListNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNewsByFilter'
type NewsRepository_ListNews_Call struct {
	*mock.Call
}

// ListNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ListNewsReq
func (_e *NewsRepository_Expecter) ListNews(ctx interface{}, req interface{}) *NewsRepository_ListNews_Call {
	return &NewsRepository_ListNews_Call{Call: _e.mock.On("ListNewsByFilter", ctx, req)}
}

func (_c *NewsRepository_ListNews_Call) Run(run func(ctx context.Context, req domain.ListNewsReq)) *NewsRepository_ListNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListNewsReq))
	})
	return _c
}

func (_c *NewsRepository_ListNews_Call) Return(_a0 []domain.ListNewsItem, _a1 error) *NewsRepository_ListNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NewsRepository_ListNews_Call) RunAndReturn(run func(context.Context, domain.ListNewsReq) ([]domain.ListNewsItem, error)) *NewsRepository_ListNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewNewsRepository creates a new instance of NewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NewsRepository {
	mock := &NewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
