-- +goose Up

CREATE TABLE "categories"
(
    "categoryId" int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(255) NOT NULL,
    "sortOrder"  int4         NOT NULL DEFAULT 0,
    "statusId"   int4         NOT NULL,
    PRIMARY KEY ("categoryId")
);

CREATE INDEX "idx_categories_sort" ON "categories" ("sortOrder", "name");


CREATE TABLE "tags"
(
    "tagId"    int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"     varchar(255) NOT NULL,
    "statusId" int4         NOT NULL,
    PRIMARY KEY ("tagId")
);

CREATE TABLE "news"
(
    "newsId"      int4                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"       text                     NOT NULL,
    "categoryId"  int4                     NOT NULL,
    "tagIds"      int4[],
    "author"      varchar(255)             NOT NULL,
    "preamble"    text                     NOT NULL,
    "content"     text,
    "createdAt"   timestamp with time zone NOT NULL DEFAULT NOW(),
    "publishedAt" timestamp with time zone NOT NULL,
    "statusId"    int4                     NOT NULL,
    PRIMARY KEY ("newsId")
);

CREATE INDEX "idx_news_category" ON "news" ("categoryId");
CREATE INDEX "idx_news_tags" ON "news" USING GIN ("tagIds");
CREATE INDEX "idx_news_published_status" ON "news" ("publishedAt", "statusId");


CREATE TABLE "statuses"
(
    "statusId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"     varchar(255),
    PRIMARY KEY ("statusId")
);


ALTER TABLE "categories"
    ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
        REFERENCES "statuses" ("statusId")
            MATCH SIMPLE
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
        NOT DEFERRABLE;

ALTER TABLE "tags"
    ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
        REFERENCES "statuses" ("statusId")
            MATCH SIMPLE
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
        NOT DEFERRABLE;

ALTER TABLE "news"
    ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
        REFERENCES "statuses" ("statusId")
            MATCH SIMPLE
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
        NOT DEFERRABLE;

ALTER TABLE "news"
    ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
        REFERENCES "categories" ("categoryId")
            MATCH SIMPLE
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
        NOT DEFERRABLE;

-- +goose Down
DROP TABLE IF EXISTS "news";
DROP TABLE IF EXISTS "tags";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "statuses";
